dist: xenial
language: c

addons:
  apt:
    packages:
      - ninja-build
      - gnu-efi
      - libpng16-dev

before_install:
  - pyenv shell 3.7
  - pip3 install --user meson

install: meson . build
script: ninja -C build

notifications:
  email: false
